### ISSUE TITLE
[Issue]: Compiler errors introduced with rccl-tests commit 77ae744 

### ISSUE THREAD

**Issue by ryanhankins** [ROCmSoftwarePlatform/rccl-tests#103]
### Problem Description

Compiler errors introduced with rccl-tests commit: 77ae744c181c02fade85b8b0536b5dba8928c461 in all_reduce.cu. ncclFp8E4M3 and ncclFp8E5M2 are undeclared identifiers in RCCL 6.0.0.

### Operating System

SUSE Linux Enterprise Server 15 SP5

### CPU

NA

### GPU

NA

### ROCm Version

ROCm 6.0.0

### Steps to Reproduce

I am building RCCL tests against ROCm 6.0 as follows:

```
git clone https://github.com/ROCmSoftwarePlatform/aws-ofi-rccl
./configure --with-libfabric=/opt/cray --with-hip=/opt/rocm-6.0.0 --with-mpi=/opt/cray/pe/mpich/8.1.29/ofi/cray/17.0
make

```

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

I get the following compiler errors when I do:

```
/scratch/jenkins/cassini/rccl_new/rccl-tests/build/hipify/all_reduce.cu.cpp:68:15: error: use of undeclared identifier 'ncclFp8E4M3'
  if((type == ncclFp8E4M3 || type == ncclFp8E5M2) && op == ncclProd)
              ^
/scratch/jenkins/cassini/rccl_new/rccl-tests/build/hipify/all_reduce.cu.cpp:68:38: error: use of undeclared identifier 'ncclFp8E5M2'
  if((type == ncclFp8E4M3 || type == ncclFp8E5M2) && op == ncclProd)
                                     ^
/scratch/jenkins/cassini/rccl_new/rccl-tests/build/hipify/all_reduce.cu.cpp:93:16: error: use of undeclared identifier 'ncclFp8E4M3'
      if((i == ncclFp8E4M3 || i == ncclFp8E5M2) && j == ncclProd)
               ^
/scratch/jenkins/cassini/rccl_new/rccl-tests/build/hipify/all_reduce.cu.cpp:93:36: error: use of undeclared identifier 'ncclFp8E5M2'
      if((i == ncclFp8E4M3 || i == ncclFp8E5M2) && j == ncclProd)
```

This appears to be introduced with this commit:

https://github.com/ROCm/rccl-tests/commit/77ae744c181c02fade85b8b0536b5dba8928c461

I was able to build by backing up to the commit immediately prior to that one.

**Comment by thananon** [comment]
I think this is resolved?

**Comment by taylding-amd** [comment]
Hi @ryanhankins,

I believe the issue has been resolved in the latest release. Could you please check and confirm so we can proceed to close the issue?

Thank you!

**Comment by ryanhankins** [comment]
I was able to build last night.  Thank you.
